### ISSUE TITLE
【不具合】毎回CIが落ちる。原因が分かる方いたら助けて下さい！！！！

### ISSUE THREAD

**Issue by ookam** [ookam/yaminabe#55]
### 不具合の種類

- [ ] デザインが崩れている
- [ ] サイトにアクセス出来ない、エラーが出る
- [ ] リンクが間違っている
- [ ] 文字の間違い、誤字がある
- [x] その他

### 動作環境は？

- [x] PC
- [ ] タブレット
- [ ] スマートフォン
- [ ] ゲーム機

### ここが不具合だと思いました！
- 毎回CIが落ちる（再実行すると正常に動く）

### こうなってほしい！
- 一発で通ってほしい

### サイト上でのURLやスクショ
- 

### 補足
- 

```
yarn run v1.22.5
$ NODE_ENV=production npm-run-all clean build:production:webpack build:production:eleventy
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1613454522179-0.8487766667999233/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @0.0.1 clean /home/runner/work/yaminabe/yaminabe
> rimraf dist

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1613454522179-0.8487766667999233/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @0.0.1 build:production:webpack /home/runner/work/yaminabe/yaminabe
> NODE_ENV=production webpack --mode=production

Hash: 0ab87cc9d00e6e8715b5
Version: webpack 4.46.0
Time: 10361ms
Built at: 02/16/2021 5:48:54 AM
                                    Asset       Size  Chunks                         Chunk Names
 javascripts.pack-7fe9c5cddef494352b93.js   3.25 KiB       0  [emitted] [immutable]  javascripts.pack
                            manifest.json  259 bytes          [emitted]              
 stylesheets.pack-051c519421c6b2f72fb6.js   1.34 KiB       1  [emitted] [immutable]  stylesheets.pack
stylesheets.pack-0ab87cc9d00e6e8715b5.css   7.95 KiB       1  [emitted] [immutable]  stylesheets.pack
Entrypoint stylesheets.pack = stylesheets.pack-0ab87cc9d00e6e8715b5.css stylesheets.pack-051c519421c6b2f72fb6.js
Entrypoint javascripts.pack = javascripts.pack-7fe9c5cddef494352b93.js
[0] ./src/packs/stylesheets/tailwind.scss 50 bytes {1} [built]
[1] ./src/packs/javascripts/index.js 103 bytes {0} [built]
[2] ./src/packs/stylesheets.pack.js 23 bytes {1} [built]
[3] ./src/packs/stylesheets/index.js 135 bytes {1} [built]
[4] ./src/packs/stylesheets sync .+\.(css|scss)$ 198 bytes {1} [built]
[5] ./src/packs/stylesheets/master.scss 50 bytes {1} [optional] [built]
[6] ./src/packs/javascripts.pack.js 23 bytes {0} [built]
[7] ./src/packs/javascripts sync .+\.(js|ts)$ 215 bytes {0} [built]
[8] ./src/packs/javascripts/rainbow.js 3.59 KiB {0} [optional] [built]
[9] ./src/packs/javascripts/set_dark_mode.js 1.36 KiB {0} [optional] [built]
    + 2 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/postcss-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js??ref--5-3!src/packs/stylesheets/master.scss:
    Entrypoint mini-css-extract-plugin = *
    [1] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/packs/stylesheets/master.scss 1.06 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/postcss-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js??ref--5-3!src/packs/stylesheets/tailwind.scss:
    Entrypoint mini-css-extract-plugin = *
    [1] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/packs/stylesheets/tailwind.scss 17 KiB {0} [built]
        + 1 hidden module
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1613454522179-0.8487766667999233/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @0.0.1 build:production:eleventy /home/runner/work/yaminabe/yaminabe
> ELEVENTY_ENV=production eleventy

TypeError: response.data.map is not a function
    at /home/runner/work/yaminabe/yaminabe/src/app/_data/contributors.js:8:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
> response.data.map is not a function

`TypeError` was thrown:
    TypeError: response.data.map is not a function
        at /home/runner/work/yaminabe/yaminabe/src/app/_data/contributors.js:8:23
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 build:production:eleventy: `ELEVENTY_ENV=production eleventy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.0.1 build:production:eleventy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-16T05_48_55_487Z-debug.log
ERROR: "build:production:eleventy" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by ookam** [comment]
多分githubから空のresponseが返ってきてる（github側のissueで上がってた）ので、空のデータが返った時はretryするようにすればこの問題は解決できそう？

promiseをretryするのってめんどくさかった記憶があるのですが、誰か分かる方いたら助けて下さい！！！！

**Comment by ookam** [comment]
無事通るようになりました！！！サンキュー @dtakkiy  ！！！🔥🔥🔥🔥
